import './js/footer';
import './js/header';
import './js/hero';
// import './js/filters';
import './js/prodacts-list';
import './js/popular-prodacts';
import './js/discount';
import './js/api';
import './js/modal';
import './js/cart';
